server:
  port: 8088


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testjava
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true